IF OBJECT_ID('dbo.Images', 'U') IS NOT NULL DROP TABLE Images;

GO

CREATE TABLE Images (
	ID int NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Name varchar(2000) NOT NULL,
	Url varchar(4000) NOT NULL,
	RequestCount int NOT NULL DEFAULT 0
);

INSERT INTO Images(Name, Url) VALUES ('10 seconds later','https://images.funplay8.com/test/10_seconds_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('10guy','https://images.funplay8.com/test/10guy.jpg');
INSERT INTO Images(Name, Url) VALUES ('12 seconds later','https://images.funplay8.com/test/12_seconds_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('15 minutes later','https://images.funplay8.com/test/15_minutes_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('1 minute 37 seconds','https://images.funplay8.com/test/1_minute_37_seconds.jpg');
INSERT INTO Images(Name, Url) VALUES ('2000 years later','https://images.funplay8.com/test/2000_years_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('3000 years later','https://images.funplay8.com/test/3000_years_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('346 minutes later','https://images.funplay8.com/test/346_minutes_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('3 28 am','https://images.funplay8.com/test/3_28_am.jpg');
INSERT INTO Images(Name, Url) VALUES ('6 half hours later','https://images.funplay8.com/test/6_half_hours_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('6 months later','https://images.funplay8.com/test/6_months_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('7 59 am','https://images.funplay8.com/test/7_59_am.jpg');
INSERT INTO Images(Name, Url) VALUES ('7 hours later','https://images.funplay8.com/test/7_hours_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('8 01 pm','https://images.funplay8.com/test/8_01_pm.jpg');
INSERT INTO Images(Name, Url) VALUES ('8 hours later','https://images.funplay8.com/test/8_hours_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('Derp Hitler','https://images.funplay8.com/test/Derp_Hitler.jpg');
INSERT INTO Images(Name, Url) VALUES ('NOPE','https://images.funplay8.com/test/NOPE.jpg');
INSERT INTO Images(Name, Url) VALUES ('OperaHat','https://images.funplay8.com/test/OperaHat.jpg');
INSERT INTO Images(Name, Url) VALUES ('angry mom','https://images.funplay8.com/test/angry_mom.jpg');
INSERT INTO Images(Name, Url) VALUES ('angry mouth','https://images.funplay8.com/test/angry_mouth.jpg');
INSERT INTO Images(Name, Url) VALUES ('angry school boy','https://images.funplay8.com/test/angry_school_boy.jpg');
INSERT INTO Images(Name, Url) VALUES ('angry shaking','https://images.funplay8.com/test/angry_shaking.jpg');
INSERT INTO Images(Name, Url) VALUES ('angry with pc','https://images.funplay8.com/test/angry_with_pc.jpg');
INSERT INTO Images(Name, Url) VALUES ('annoying childhood friend','https://images.funplay8.com/test/annoying_childhood_friend.jpg');
INSERT INTO Images(Name, Url) VALUES ('annoying facebook girl','https://images.funplay8.com/test/annoying_facebook_girl.jpg');
INSERT INTO Images(Name, Url) VALUES ('anonymous mask','https://images.funplay8.com/test/anonymous_mask.jpg');
INSERT INTO Images(Name, Url) VALUES ('anti joke chicken','https://images.funplay8.com/test/anti_joke_chicken.jpg');
INSERT INTO Images(Name, Url) VALUES ('RedditAlien','https://images.funplay8.com/test/RedditAlien.jpg');
INSERT INTO Images(Name, Url) VALUES ('RedditAlien2','https://images.funplay8.com/test/RedditAlien2.jpg');
INSERT INTO Images(Name, Url) VALUES ('RedditAlien3','https://images.funplay8.com/test/RedditAlien3.jpg');
INSERT INTO Images(Name, Url) VALUES ('a few inches later','https://images.funplay8.com/test/a_few_inches_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('a few minutes later','https://images.funplay8.com/test/a_few_minutes_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('a few moments later','https://images.funplay8.com/test/a_few_moments_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('accidentally open internet explorer','https://images.funplay8.com/test/accidentally_open_internet_explorer.jpg');
INSERT INTO Images(Name, Url) VALUES ('actually','https://images.funplay8.com/test/actually.jpg');
INSERT INTO Images(Name, Url) VALUES ('advice dog','https://images.funplay8.com/test/advice_dog.jpg');
INSERT INTO Images(Name, Url) VALUES ('advice god','https://images.funplay8.com/test/advice_god.jpg');
INSERT INTO Images(Name, Url) VALUES ('advice yoda gives','https://images.funplay8.com/test/advice_yoda_gives.jpg');
INSERT INTO Images(Name, Url) VALUES ('aint that some shit','https://images.funplay8.com/test/aint_that_some_shit.jpg');
INSERT INTO Images(Name, Url) VALUES ('alien','https://images.funplay8.com/test/alien.jpg');
INSERT INTO Images(Name, Url) VALUES ('all the things fuu','https://images.funplay8.com/test/all_the_things_fuu.jpg');
INSERT INTO Images(Name, Url) VALUES ('all the things sad','https://images.funplay8.com/test/all_the_things_sad.jpg');
INSERT INTO Images(Name, Url) VALUES ('angry bang','https://images.funplay8.com/test/angry_bang.jpg');
INSERT INTO Images(Name, Url) VALUES ('angry dark stare','https://images.funplay8.com/test/angry_dark_stare.jpg');
INSERT INTO Images(Name, Url) VALUES ('angry head shake','https://images.funplay8.com/test/angry_head_shake.jpg');
INSERT INTO Images(Name, Url) VALUES ('3 days later','https://images.funplay8.com/test/3_days_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('3 days later 2','https://images.funplay8.com/test/3_days_later_2.jpg');
INSERT INTO Images(Name, Url) VALUES ('3 days later 3','https://images.funplay8.com/test/3_days_later_3.jpg');
INSERT INTO Images(Name, Url) VALUES ('3 days later 4','https://images.funplay8.com/test/3_days_later_4.jpg');
INSERT INTO Images(Name, Url) VALUES ('3 days later 5','https://images.funplay8.com/test/3_days_later_5.jpg');
INSERT INTO Images(Name, Url) VALUES ('3 hours later','https://images.funplay8.com/test/3_hours_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('48 hours later','https://images.funplay8.com/test/48_hours_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('4 to 6 weeks later','https://images.funplay8.com/test/4_to_6_weeks_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('5 minutes later','https://images.funplay8.com/test/5_minutes_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('are you fucking kidding me','https://images.funplay8.com/test/are_you_fucking_kidding_me.jpg');
INSERT INTO Images(Name, Url) VALUES ('are you fucking kidding me clean','https://images.funplay8.com/test/are_you_fucking_kidding_me_clean.jpg');
INSERT INTO Images(Name, Url) VALUES ('arrow in knee','https://images.funplay8.com/test/arrow_in_knee.jpg');
INSERT INTO Images(Name, Url) VALUES ('art student owl','https://images.funplay8.com/test/art_student_owl.jpg');
INSERT INTO Images(Name, Url) VALUES ('awkward moment','https://images.funplay8.com/test/awkward_moment.jpg');
INSERT INTO Images(Name, Url) VALUES ('aww yeah','https://images.funplay8.com/test/aww_yeah.jpg');
INSERT INTO Images(Name, Url) VALUES ('baby godfather','https://images.funplay8.com/test/baby_godfather.jpg');
INSERT INTO Images(Name, Url) VALUES ('baby troll','https://images.funplay8.com/test/baby_troll.jpg');
INSERT INTO Images(Name, Url) VALUES ('bad advice cat','https://images.funplay8.com/test/bad_advice_cat.jpg');
INSERT INTO Images(Name, Url) VALUES ('black big smile','https://images.funplay8.com/test/black_big_smile.jpg');
INSERT INTO Images(Name, Url) VALUES ('black concentrated','https://images.funplay8.com/test/black_concentrated.jpg');
INSERT INTO Images(Name, Url) VALUES ('black crying','https://images.funplay8.com/test/black_crying.jpg');
INSERT INTO Images(Name, Url) VALUES ('black dazed','https://images.funplay8.com/test/black_dazed.jpg');
INSERT INTO Images(Name, Url) VALUES ('black determined','https://images.funplay8.com/test/black_determined.jpg');
INSERT INTO Images(Name, Url) VALUES ('black dude','https://images.funplay8.com/test/black_dude.jpg');
INSERT INTO Images(Name, Url) VALUES ('black dumbfounded','https://images.funplay8.com/test/black_dumbfounded.jpg');
INSERT INTO Images(Name, Url) VALUES ('black ewbte','https://images.funplay8.com/test/black_ewbte.jpg');
INSERT INTO Images(Name, Url) VALUES ('black excited','https://images.funplay8.com/test/black_excited.jpg');
INSERT INTO Images(Name, Url) VALUES ('black excited bliss','https://images.funplay8.com/test/black_excited_bliss.jpg');
INSERT INTO Images(Name, Url) VALUES ('black excited tears','https://images.funplay8.com/test/black_excited_tears.jpg');
INSERT INTO Images(Name, Url) VALUES ('black facepalm','https://images.funplay8.com/test/black_facepalm.jpg');
INSERT INTO Images(Name, Url) VALUES ('black fake smile','https://images.funplay8.com/test/black_fake_smile.jpg');
INSERT INTO Images(Name, Url) VALUES ('black forever alone','https://images.funplay8.com/test/black_forever_alone.jpg');
INSERT INTO Images(Name, Url) VALUES ('black freddie','https://images.funplay8.com/test/black_freddie.jpg');
INSERT INTO Images(Name, Url) VALUES ('black fuck that bitch','https://images.funplay8.com/test/black_fuck_that_bitch.jpg');
INSERT INTO Images(Name, Url) VALUES ('black fuck yeah','https://images.funplay8.com/test/black_fuck_yeah.jpg');
INSERT INTO Images(Name, Url) VALUES ('black gasp','https://images.funplay8.com/test/black_gasp.jpg');
INSERT INTO Images(Name, Url) VALUES ('black me gusta','https://images.funplay8.com/test/black_me_gusta.jpg');
INSERT INTO Images(Name, Url) VALUES ('black milk','https://images.funplay8.com/test/black_milk.jpg');
INSERT INTO Images(Name, Url) VALUES ('black normal','https://images.funplay8.com/test/black_normal.jpg');
INSERT INTO Images(Name, Url) VALUES ('black normal2','https://images.funplay8.com/test/black_normal2.jpg');
INSERT INTO Images(Name, Url) VALUES ('black okay','https://images.funplay8.com/test/black_okay.jpg');
INSERT INTO Images(Name, Url) VALUES ('black omgrun','https://images.funplay8.com/test/black_omgrun.jpg');
INSERT INTO Images(Name, Url) VALUES ('black pfft','https://images.funplay8.com/test/black_pfft.jpg');
INSERT INTO Images(Name, Url) VALUES ('black quite','https://images.funplay8.com/test/black_quite.jpg');
INSERT INTO Images(Name, Url) VALUES ('black rage','https://images.funplay8.com/test/black_rage.jpg');
INSERT INTO Images(Name, Url) VALUES ('black gasp2','https://images.funplay8.com/test/black_gasp2.jpg');
INSERT INTO Images(Name, Url) VALUES ('black guy gun','https://images.funplay8.com/test/black_guy_gun.jpg');
INSERT INTO Images(Name, Url) VALUES ('black happy','https://images.funplay8.com/test/black_happy.jpg');
INSERT INTO Images(Name, Url) VALUES ('black hmmm','https://images.funplay8.com/test/black_hmmm.jpg');
INSERT INTO Images(Name, Url) VALUES ('black i wonder','https://images.funplay8.com/test/black_i_wonder.jpg');
INSERT INTO Images(Name, Url) VALUES ('black ladystare','https://images.funplay8.com/test/black_ladystare.jpg');
INSERT INTO Images(Name, Url) VALUES ('black ladystare2','https://images.funplay8.com/test/black_ladystare2.jpg');
INSERT INTO Images(Name, Url) VALUES ('black lean','https://images.funplay8.com/test/black_lean.jpg');
INSERT INTO Images(Name, Url) VALUES ('black lol','https://images.funplay8.com/test/black_lol.jpg');
INSERT INTO Images(Name, Url) VALUES ('bad luck brian','https://images.funplay8.com/test/bad_luck_brian.jpg');
INSERT INTO Images(Name, Url) VALUES ('bad pokerface','https://images.funplay8.com/test/bad_pokerface.jpg');
INSERT INTO Images(Name, Url) VALUES ('bear grylls','https://images.funplay8.com/test/bear_grylls.jpg');
INSERT INTO Images(Name, Url) VALUES ('beard guy','https://images.funplay8.com/test/beard_guy.jpg');
INSERT INTO Images(Name, Url) VALUES ('beer guy','https://images.funplay8.com/test/beer_guy.jpg');
INSERT INTO Images(Name, Url) VALUES ('beng','https://images.funplay8.com/test/beng.jpg');
INSERT INTO Images(Name, Url) VALUES ('big smile','https://images.funplay8.com/test/big_smile.jpg');
INSERT INTO Images(Name, Url) VALUES ('bill oreilly','https://images.funplay8.com/test/bill_oreilly.jpg');
INSERT INTO Images(Name, Url) VALUES ('bitchslap','https://images.funplay8.com/test/bitchslap.jpg');
INSERT INTO Images(Name, Url) VALUES ('black rage2','https://images.funplay8.com/test/black_rage2.jpg');
INSERT INTO Images(Name, Url) VALUES ('black rage canadian','https://images.funplay8.com/test/black_rage_canadian.jpg');
INSERT INTO Images(Name, Url) VALUES ('black rage extreme','https://images.funplay8.com/test/black_rage_extreme.jpg');
INSERT INTO Images(Name, Url) VALUES ('black rage extreme2','https://images.funplay8.com/test/black_rage_extreme2.jpg');
INSERT INTO Images(Name, Url) VALUES ('black rage foaming','https://images.funplay8.com/test/black_rage_foaming.jpg');
INSERT INTO Images(Name, Url) VALUES ('black rage getting pissed','https://images.funplay8.com/test/black_rage_getting_pissed.jpg');
INSERT INTO Images(Name, Url) VALUES ('black rage mad','https://images.funplay8.com/test/black_rage_mad.jpg');
INSERT INTO Images(Name, Url) VALUES ('black rage mad2','https://images.funplay8.com/test/black_rage_mad2.jpg');
INSERT INTO Images(Name, Url) VALUES ('black rage quiet','https://images.funplay8.com/test/black_rage_quiet.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde excited bliss','https://images.funplay8.com/test/blonde_excited_bliss.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde excited tears','https://images.funplay8.com/test/blonde_excited_tears.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde facepalm','https://images.funplay8.com/test/blonde_facepalm.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde fake smile','https://images.funplay8.com/test/blonde_fake_smile.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde forever alone','https://images.funplay8.com/test/blonde_forever_alone.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde freddie','https://images.funplay8.com/test/blonde_freddie.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde fuck that bitch','https://images.funplay8.com/test/blonde_fuck_that_bitch.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde fuck yeah','https://images.funplay8.com/test/blonde_fuck_yeah.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde gasp','https://images.funplay8.com/test/blonde_gasp.jpg');
INSERT INTO Images(Name, Url) VALUES ('black rage shaking','https://images.funplay8.com/test/black_rage_shaking.jpg');
INSERT INTO Images(Name, Url) VALUES ('black rage super','https://images.funplay8.com/test/black_rage_super.jpg');
INSERT INTO Images(Name, Url) VALUES ('black really determined','https://images.funplay8.com/test/black_really_determined.jpg');
INSERT INTO Images(Name, Url) VALUES ('black red tongue','https://images.funplay8.com/test/black_red_tongue.jpg');
INSERT INTO Images(Name, Url) VALUES ('black schlick','https://images.funplay8.com/test/black_schlick.jpg');
INSERT INTO Images(Name, Url) VALUES ('black smile','https://images.funplay8.com/test/black_smile.jpg');
INSERT INTO Images(Name, Url) VALUES ('black sweet tears','https://images.funplay8.com/test/black_sweet_tears.jpg');
INSERT INTO Images(Name, Url) VALUES ('black tongue down','https://images.funplay8.com/test/black_tongue_down.jpg');
INSERT INTO Images(Name, Url) VALUES ('black troll','https://images.funplay8.com/test/black_troll.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde gasp2','https://images.funplay8.com/test/blonde_gasp2.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde genius','https://images.funplay8.com/test/blonde_genius.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde happy','https://images.funplay8.com/test/blonde_happy.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde hmmm','https://images.funplay8.com/test/blonde_hmmm.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde i wonder','https://images.funplay8.com/test/blonde_i_wonder.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde ladystare','https://images.funplay8.com/test/blonde_ladystare.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde ladystare2','https://images.funplay8.com/test/blonde_ladystare2.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde lean','https://images.funplay8.com/test/blonde_lean.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde lol','https://images.funplay8.com/test/blonde_lol.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde big smile','https://images.funplay8.com/test/blonde_big_smile.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde concentrated','https://images.funplay8.com/test/blonde_concentrated.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde crying','https://images.funplay8.com/test/blonde_crying.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde dazed','https://images.funplay8.com/test/blonde_dazed.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde determined','https://images.funplay8.com/test/blonde_determined.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde dude','https://images.funplay8.com/test/blonde_dude.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde dumbfounded','https://images.funplay8.com/test/blonde_dumbfounded.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde ewbte','https://images.funplay8.com/test/blonde_ewbte.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde excited','https://images.funplay8.com/test/blonde_excited.jpg');
INSERT INTO Images(Name, Url) VALUES ('black troll sad','https://images.funplay8.com/test/black_troll_sad.jpg');
INSERT INTO Images(Name, Url) VALUES ('black what','https://images.funplay8.com/test/black_what.jpg');
INSERT INTO Images(Name, Url) VALUES ('black why','https://images.funplay8.com/test/black_why.jpg');
INSERT INTO Images(Name, Url) VALUES ('black why no hands','https://images.funplay8.com/test/black_why_no_hands.jpg');
INSERT INTO Images(Name, Url) VALUES ('black wut','https://images.funplay8.com/test/black_wut.jpg');
INSERT INTO Images(Name, Url) VALUES ('blackhair','https://images.funplay8.com/test/blackhair.jpg');
INSERT INTO Images(Name, Url) VALUES ('blackhair2','https://images.funplay8.com/test/blackhair2.jpg');
INSERT INTO Images(Name, Url) VALUES ('blackhair3','https://images.funplay8.com/test/blackhair3.jpg');
INSERT INTO Images(Name, Url) VALUES ('blankhair','https://images.funplay8.com/test/blankhair.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde me gusta','https://images.funplay8.com/test/blonde_me_gusta.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde milk','https://images.funplay8.com/test/blonde_milk.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde normal','https://images.funplay8.com/test/blonde_normal.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde normal2','https://images.funplay8.com/test/blonde_normal2.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde okay','https://images.funplay8.com/test/blonde_okay.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde omgrun','https://images.funplay8.com/test/blonde_omgrun.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde pfft','https://images.funplay8.com/test/blonde_pfft.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde quite','https://images.funplay8.com/test/blonde_quite.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde rage','https://images.funplay8.com/test/blonde_rage.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde rage2','https://images.funplay8.com/test/blonde_rage2.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde rage canadian','https://images.funplay8.com/test/blonde_rage_canadian.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde rage extreme','https://images.funplay8.com/test/blonde_rage_extreme.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde rage extreme2','https://images.funplay8.com/test/blonde_rage_extreme2.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde rage foaming','https://images.funplay8.com/test/blonde_rage_foaming.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde rage getting pissed','https://images.funplay8.com/test/blonde_rage_getting_pissed.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde rage mad','https://images.funplay8.com/test/blonde_rage_mad.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde rage mad2','https://images.funplay8.com/test/blonde_rage_mad2.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde rage quiet','https://images.funplay8.com/test/blonde_rage_quiet.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde rage shaking','https://images.funplay8.com/test/blonde_rage_shaking.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde rage super','https://images.funplay8.com/test/blonde_rage_super.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde really determined','https://images.funplay8.com/test/blonde_really_determined.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde red tongue','https://images.funplay8.com/test/blonde_red_tongue.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde schlick','https://images.funplay8.com/test/blonde_schlick.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde smile','https://images.funplay8.com/test/blonde_smile.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde sweet tears','https://images.funplay8.com/test/blonde_sweet_tears.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde tongue down','https://images.funplay8.com/test/blonde_tongue_down.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde troll','https://images.funplay8.com/test/blonde_troll.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde troll sad','https://images.funplay8.com/test/blonde_troll_sad.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde what','https://images.funplay8.com/test/blonde_what.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde why','https://images.funplay8.com/test/blonde_why.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde why no hands','https://images.funplay8.com/test/blonde_why_no_hands.jpg');
INSERT INTO Images(Name, Url) VALUES ('blonde wut','https://images.funplay8.com/test/blonde_wut.jpg');
INSERT INTO Images(Name, Url) VALUES ('blondehair','https://images.funplay8.com/test/blondehair.jpg');
INSERT INTO Images(Name, Url) VALUES ('blue y u no','https://images.funplay8.com/test/blue_y_u_no.jpg');
INSERT INTO Images(Name, Url) VALUES ('blushing','https://images.funplay8.com/test/blushing.jpg');
INSERT INTO Images(Name, Url) VALUES ('boobs','https://images.funplay8.com/test/boobs.jpg');
INSERT INTO Images(Name, Url) VALUES ('brace yourselves x is coming','https://images.funplay8.com/test/brace_yourselves_x_is_coming.jpg');
INSERT INTO Images(Name, Url) VALUES ('brad pitt','https://images.funplay8.com/test/brad_pitt.jpg');
INSERT INTO Images(Name, Url) VALUES ('brant rules','https://images.funplay8.com/test/brant_rules.jpg');
INSERT INTO Images(Name, Url) VALUES ('broken heart','https://images.funplay8.com/test/broken_heart.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette big smile','https://images.funplay8.com/test/brunette_big_smile.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette concentrated','https://images.funplay8.com/test/brunette_concentrated.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette crying','https://images.funplay8.com/test/brunette_crying.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette dazed','https://images.funplay8.com/test/brunette_dazed.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette determined','https://images.funplay8.com/test/brunette_determined.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette dude','https://images.funplay8.com/test/brunette_dude.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette dumbfounded','https://images.funplay8.com/test/brunette_dumbfounded.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette ewbte','https://images.funplay8.com/test/brunette_ewbte.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette excited','https://images.funplay8.com/test/brunette_excited.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette excited bliss','https://images.funplay8.com/test/brunette_excited_bliss.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette excited tears','https://images.funplay8.com/test/brunette_excited_tears.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette facepalm','https://images.funplay8.com/test/brunette_facepalm.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette fake smile','https://images.funplay8.com/test/brunette_fake_smile.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette forever alone','https://images.funplay8.com/test/brunette_forever_alone.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette freddie','https://images.funplay8.com/test/brunette_freddie.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette fuck that bitch','https://images.funplay8.com/test/brunette_fuck_that_bitch.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette fuck yeah','https://images.funplay8.com/test/brunette_fuck_yeah.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette gasp','https://images.funplay8.com/test/brunette_gasp.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette gasp2','https://images.funplay8.com/test/brunette_gasp2.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette happy','https://images.funplay8.com/test/brunette_happy.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette hmmm','https://images.funplay8.com/test/brunette_hmmm.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette i wonder','https://images.funplay8.com/test/brunette_i_wonder.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette ladystare','https://images.funplay8.com/test/brunette_ladystare.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette ladystare2','https://images.funplay8.com/test/brunette_ladystare2.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette lean','https://images.funplay8.com/test/brunette_lean.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette lol','https://images.funplay8.com/test/brunette_lol.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette me gusta','https://images.funplay8.com/test/brunette_me_gusta.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette milk','https://images.funplay8.com/test/brunette_milk.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette normal','https://images.funplay8.com/test/brunette_normal.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette normal2','https://images.funplay8.com/test/brunette_normal2.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette okay','https://images.funplay8.com/test/brunette_okay.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette omgrun','https://images.funplay8.com/test/brunette_omgrun.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette pfft','https://images.funplay8.com/test/brunette_pfft.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette quite','https://images.funplay8.com/test/brunette_quite.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette rage','https://images.funplay8.com/test/brunette_rage.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette rage2','https://images.funplay8.com/test/brunette_rage2.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette rage canadian','https://images.funplay8.com/test/brunette_rage_canadian.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette rage extreme','https://images.funplay8.com/test/brunette_rage_extreme.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette rage extreme2','https://images.funplay8.com/test/brunette_rage_extreme2.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette rage foaming','https://images.funplay8.com/test/brunette_rage_foaming.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette rage getting pissed','https://images.funplay8.com/test/brunette_rage_getting_pissed.jpg');
INSERT INTO Images(Name, Url) VALUES ('butthurt dweller','https://images.funplay8.com/test/butthurt_dweller.jpg');
INSERT INTO Images(Name, Url) VALUES ('canadian rage','https://images.funplay8.com/test/canadian_rage.jpg');
INSERT INTO Images(Name, Url) VALUES ('cat chin','https://images.funplay8.com/test/cat_chin.jpg');
INSERT INTO Images(Name, Url) VALUES ('cat cuteness overload','https://images.funplay8.com/test/cat_cuteness_overload.jpg');
INSERT INTO Images(Name, Url) VALUES ('cat gasp','https://images.funplay8.com/test/cat_gasp.jpg');
INSERT INTO Images(Name, Url) VALUES ('cereal guy','https://images.funplay8.com/test/cereal_guy.jpg');
INSERT INTO Images(Name, Url) VALUES ('cereal guy angry','https://images.funplay8.com/test/cereal_guy_angry.jpg');
INSERT INTO Images(Name, Url) VALUES ('cereal guy big squint','https://images.funplay8.com/test/cereal_guy_big_squint.jpg');
INSERT INTO Images(Name, Url) VALUES ('cereal guy drink sip','https://images.funplay8.com/test/cereal_guy_drink_sip.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette tongue down','https://images.funplay8.com/test/brunette_tongue_down.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette troll','https://images.funplay8.com/test/brunette_troll.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette troll sad','https://images.funplay8.com/test/brunette_troll_sad.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette what','https://images.funplay8.com/test/brunette_what.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette why','https://images.funplay8.com/test/brunette_why.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette why no hands','https://images.funplay8.com/test/brunette_why_no_hands.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette wut','https://images.funplay8.com/test/brunette_wut.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunettehair','https://images.funplay8.com/test/brunettehair.jpg');
INSERT INTO Images(Name, Url) VALUES ('business cat','https://images.funplay8.com/test/business_cat.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette rage mad','https://images.funplay8.com/test/brunette_rage_mad.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette rage mad2','https://images.funplay8.com/test/brunette_rage_mad2.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette rage quiet','https://images.funplay8.com/test/brunette_rage_quiet.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette rage shaking','https://images.funplay8.com/test/brunette_rage_shaking.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette really determined','https://images.funplay8.com/test/brunette_really_determined.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette red tongue','https://images.funplay8.com/test/brunette_red_tongue.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette schlick','https://images.funplay8.com/test/brunette_schlick.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette smile','https://images.funplay8.com/test/brunette_smile.jpg');
INSERT INTO Images(Name, Url) VALUES ('brunette sweet tears','https://images.funplay8.com/test/brunette_sweet_tears.jpg');
INSERT INTO Images(Name, Url) VALUES ('cereal guy original','https://images.funplay8.com/test/cereal_guy_original.jpg');
INSERT INTO Images(Name, Url) VALUES ('cereal guy spitting','https://images.funplay8.com/test/cereal_guy_spitting.jpg');
INSERT INTO Images(Name, Url) VALUES ('cereal guy squint','https://images.funplay8.com/test/cereal_guy_squint.jpg');
INSERT INTO Images(Name, Url) VALUES ('challenge accepted','https://images.funplay8.com/test/challenge_accepted.jpg');
INSERT INTO Images(Name, Url) VALUES ('challenge accepted drunk','https://images.funplay8.com/test/challenge_accepted_drunk.jpg');
INSERT INTO Images(Name, Url) VALUES ('challenge considered','https://images.funplay8.com/test/challenge_considered.jpg');
INSERT INTO Images(Name, Url) VALUES ('challenge denied','https://images.funplay8.com/test/challenge_denied.jpg');
INSERT INTO Images(Name, Url) VALUES ('challenge failed','https://images.funplay8.com/test/challenge_failed.jpg');
INSERT INTO Images(Name, Url) VALUES ('chef hat','https://images.funplay8.com/test/chef_hat.jpg');
INSERT INTO Images(Name, Url) VALUES ('concentrated','https://images.funplay8.com/test/concentrated.jpg');
INSERT INTO Images(Name, Url) VALUES ('concentrated teeth','https://images.funplay8.com/test/concentrated_teeth.jpg');
INSERT INTO Images(Name, Url) VALUES ('conflicting emotions','https://images.funplay8.com/test/conflicting_emotions.jpg');
INSERT INTO Images(Name, Url) VALUES ('conspiracy keanu','https://images.funplay8.com/test/conspiracy_keanu.jpg');
INSERT INTO Images(Name, Url) VALUES ('cook fap','https://images.funplay8.com/test/cook_fap.jpg');
INSERT INTO Images(Name, Url) VALUES ('courage wolf','https://images.funplay8.com/test/courage_wolf.jpg');
INSERT INTO Images(Name, Url) VALUES ('crazy rage','https://images.funplay8.com/test/crazy_rage.jpg');
INSERT INTO Images(Name, Url) VALUES ('creepy dark','https://images.funplay8.com/test/creepy_dark.jpg');
INSERT INTO Images(Name, Url) VALUES ('creepy glasses guy','https://images.funplay8.com/test/creepy_glasses_guy.jpg');
INSERT INTO Images(Name, Url) VALUES ('chemistry cat','https://images.funplay8.com/test/chemistry_cat.jpg');
INSERT INTO Images(Name, Url) VALUES ('chin strapping','https://images.funplay8.com/test/chin_strapping.jpg');
INSERT INTO Images(Name, Url) VALUES ('classic rage','https://images.funplay8.com/test/classic_rage.jpg');
INSERT INTO Images(Name, Url) VALUES ('clean everything','https://images.funplay8.com/test/clean_everything.jpg');
INSERT INTO Images(Name, Url) VALUES ('clever girl','https://images.funplay8.com/test/clever_girl.jpg');
INSERT INTO Images(Name, Url) VALUES ('college liberal','https://images.funplay8.com/test/college_liberal.jpg');
INSERT INTO Images(Name, Url) VALUES ('computer slice','https://images.funplay8.com/test/computer_slice.jpg');
INSERT INTO Images(Name, Url) VALUES ('computer stare','https://images.funplay8.com/test/computer_stare.jpg');
INSERT INTO Images(Name, Url) VALUES ('concentrate','https://images.funplay8.com/test/concentrate.jpg');
INSERT INTO Images(Name, Url) VALUES ('creepy troll','https://images.funplay8.com/test/creepy_troll.jpg');
INSERT INTO Images(Name, Url) VALUES ('cry pc','https://images.funplay8.com/test/cry_pc.jpg');
INSERT INTO Images(Name, Url) VALUES ('crying','https://images.funplay8.com/test/crying.jpg');
INSERT INTO Images(Name, Url) VALUES ('cute kid','https://images.funplay8.com/test/cute_kid.jpg');
INSERT INTO Images(Name, Url) VALUES ('cute little kid','https://images.funplay8.com/test/cute_little_kid.jpg');
INSERT INTO Images(Name, Url) VALUES ('cuteness overload','https://images.funplay8.com/test/cuteness_overload.jpg');
INSERT INTO Images(Name, Url) VALUES ('cuteness overload 2','https://images.funplay8.com/test/cuteness_overload_2.jpg');
INSERT INTO Images(Name, Url) VALUES ('daily lie','https://images.funplay8.com/test/daily_lie.jpg');
INSERT INTO Images(Name, Url) VALUES ('damn','https://images.funplay8.com/test/damn.jpg');
INSERT INTO Images(Name, Url) VALUES ('dat ash','https://images.funplay8.com/test/dat_ash.jpg');
INSERT INTO Images(Name, Url) VALUES ('dat ass','https://images.funplay8.com/test/dat_ass.jpg');
INSERT INTO Images(Name, Url) VALUES ('dating site murderer','https://images.funplay8.com/test/dating_site_murderer.jpg');
INSERT INTO Images(Name, Url) VALUES ('day four','https://images.funplay8.com/test/day_four.jpg');
INSERT INTO Images(Name, Url) VALUES ('day three','https://images.funplay8.com/test/day_three.jpg');
INSERT INTO Images(Name, Url) VALUES ('day two','https://images.funplay8.com/test/day_two.jpg');
INSERT INTO Images(Name, Url) VALUES ('depression dog','https://images.funplay8.com/test/depression_dog.jpg');
INSERT INTO Images(Name, Url) VALUES ('derp gusta','https://images.funplay8.com/test/derp_gusta.jpg');
INSERT INTO Images(Name, Url) VALUES ('derpina','https://images.funplay8.com/test/derpina.jpg');
INSERT INTO Images(Name, Url) VALUES ('duck yeah','https://images.funplay8.com/test/duck_yeah.jpg');
INSERT INTO Images(Name, Url) VALUES ('duckface','https://images.funplay8.com/test/duckface.jpg');
INSERT INTO Images(Name, Url) VALUES ('dude','https://images.funplay8.com/test/dude.jpg');
INSERT INTO Images(Name, Url) VALUES ('dude come on','https://images.funplay8.com/test/dude_come_on.jpg');
INSERT INTO Images(Name, Url) VALUES ('dwight schrute','https://images.funplay8.com/test/dwight_schrute.jpg');
INSERT INTO Images(Name, Url) VALUES ('efl troll face','https://images.funplay8.com/test/efl_troll_face.jpg');
INSERT INTO Images(Name, Url) VALUES ('eight hours later','https://images.funplay8.com/test/eight_hours_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('embrace pc','https://images.funplay8.com/test/embrace_pc.jpg');
INSERT INTO Images(Name, Url) VALUES ('epic win','https://images.funplay8.com/test/epic_win.jpg');
INSERT INTO Images(Name, Url) VALUES ('derpina eyes closed','https://images.funplay8.com/test/derpina_eyes_closed.jpg');
INSERT INTO Images(Name, Url) VALUES ('desk flip','https://images.funplay8.com/test/desk_flip.jpg');
INSERT INTO Images(Name, Url) VALUES ('devil','https://images.funplay8.com/test/devil.jpg');
INSERT INTO Images(Name, Url) VALUES ('disaster girl','https://images.funplay8.com/test/disaster_girl.jpg');
INSERT INTO Images(Name, Url) VALUES ('dog wetodd','https://images.funplay8.com/test/dog_wetodd.jpg');
INSERT INTO Images(Name, Url) VALUES ('dolan','https://images.funplay8.com/test/dolan.jpg');
INSERT INTO Images(Name, Url) VALUES ('double facepalm','https://images.funplay8.com/test/double_facepalm.jpg');
INSERT INTO Images(Name, Url) VALUES ('drinkin coke','https://images.funplay8.com/test/drinkin_coke.jpg');
INSERT INTO Images(Name, Url) VALUES ('drunk baby','https://images.funplay8.com/test/drunk_baby.jpg');
INSERT INTO Images(Name, Url) VALUES ('eventually','https://images.funplay8.com/test/eventually.jpg');
INSERT INTO Images(Name, Url) VALUES ('everything is beatiful','https://images.funplay8.com/test/everything_is_beatiful.jpg');
INSERT INTO Images(Name, Url) VALUES ('everything went better','https://images.funplay8.com/test/everything_went_better.jpg');
INSERT INTO Images(Name, Url) VALUES ('evil cows','https://images.funplay8.com/test/evil_cows.jpg');
INSERT INTO Images(Name, Url) VALUES ('evil smile','https://images.funplay8.com/test/evil_smile.jpg');
INSERT INTO Images(Name, Url) VALUES ('eye half closed','https://images.funplay8.com/test/eye_half_closed.jpg');
INSERT INTO Images(Name, Url) VALUES ('eyebrow look','https://images.funplay8.com/test/eyebrow_look.jpg');
INSERT INTO Images(Name, Url) VALUES ('fabulous','https://images.funplay8.com/test/fabulous.jpg');
INSERT INTO Images(Name, Url) VALUES ('face mustache','https://images.funplay8.com/test/face_mustache.jpg');
INSERT INTO Images(Name, Url) VALUES ('facepalm','https://images.funplay8.com/test/facepalm.jpg');
INSERT INTO Images(Name, Url) VALUES ('facepalm female','https://images.funplay8.com/test/facepalm_female.jpg');
INSERT INTO Images(Name, Url) VALUES ('facepalm picard','https://images.funplay8.com/test/facepalm_picard.jpg');
INSERT INTO Images(Name, Url) VALUES ('faces together','https://images.funplay8.com/test/faces_together.jpg');
INSERT INTO Images(Name, Url) VALUES ('fap','https://images.funplay8.com/test/fap.jpg');
INSERT INTO Images(Name, Url) VALUES ('fap accepted','https://images.funplay8.com/test/fap_accepted.jpg');
INSERT INTO Images(Name, Url) VALUES ('fap gentleman','https://images.funplay8.com/test/fap_gentleman.jpg');
INSERT INTO Images(Name, Url) VALUES ('fap schlick female','https://images.funplay8.com/test/fap_schlick_female.jpg');
INSERT INTO Images(Name, Url) VALUES ('fap scream','https://images.funplay8.com/test/fap_scream.jpg');
INSERT INTO Images(Name, Url) VALUES ('feel like a ninja','https://images.funplay8.com/test/feel_like_a_ninja.jpg');
INSERT INTO Images(Name, Url) VALUES ('feels good man','https://images.funplay8.com/test/feels_good_man.jpg');
INSERT INTO Images(Name, Url) VALUES ('female aww yeah','https://images.funplay8.com/test/female_aww_yeah.jpg');
INSERT INTO Images(Name, Url) VALUES ('female rage','https://images.funplay8.com/test/female_rage.jpg');
INSERT INTO Images(Name, Url) VALUES ('female seriously glasses','https://images.funplay8.com/test/female_seriously_glasses.jpg');
INSERT INTO Images(Name, Url) VALUES ('fffffffuuuuuuuuuuuu','https://images.funplay8.com/test/fffffffuuuuuuuuuuuu.jpg');
INSERT INTO Images(Name, Url) VALUES ('first world problems','https://images.funplay8.com/test/first_world_problems.jpg');
INSERT INTO Images(Name, Url) VALUES ('forever a gamer','https://images.funplay8.com/test/forever_a_gamer.jpg');
INSERT INTO Images(Name, Url) VALUES ('forever alone','https://images.funplay8.com/test/forever_alone.jpg');
INSERT INTO Images(Name, Url) VALUES ('freddie girl','https://images.funplay8.com/test/freddie_girl.jpg');
INSERT INTO Images(Name, Url) VALUES ('freddie mercury','https://images.funplay8.com/test/freddie_mercury.jpg');
INSERT INTO Images(Name, Url) VALUES ('french','https://images.funplay8.com/test/french.jpg');
INSERT INTO Images(Name, Url) VALUES ('frogman','https://images.funplay8.com/test/frogman.jpg');
INSERT INTO Images(Name, Url) VALUES ('frogman happy','https://images.funplay8.com/test/frogman_happy.jpg');
INSERT INTO Images(Name, Url) VALUES ('frogman sad','https://images.funplay8.com/test/frogman_sad.jpg');
INSERT INTO Images(Name, Url) VALUES ('frown','https://images.funplay8.com/test/frown.jpg');
INSERT INTO Images(Name, Url) VALUES ('fsjal','https://images.funplay8.com/test/fsjal.jpg');
INSERT INTO Images(Name, Url) VALUES ('fuck that','https://images.funplay8.com/test/fuck_that.jpg');
INSERT INTO Images(Name, Url) VALUES ('fuck that bitch yao pff','https://images.funplay8.com/test/fuck_that_bitch_yao_pff.jpg');
INSERT INTO Images(Name, Url) VALUES ('fuck that shit female','https://images.funplay8.com/test/fuck_that_shit_female.jpg');
INSERT INTO Images(Name, Url) VALUES ('fuck that yao ming','https://images.funplay8.com/test/fuck_that_yao_ming.jpg');
INSERT INTO Images(Name, Url) VALUES ('fuck yeah','https://images.funplay8.com/test/fuck_yeah.jpg');
INSERT INTO Images(Name, Url) VALUES ('fuck yeah clean','https://images.funplay8.com/test/fuck_yeah_clean.jpg');
INSERT INTO Images(Name, Url) VALUES ('fuck yeah close enough','https://images.funplay8.com/test/fuck_yeah_close_enough.jpg');
INSERT INTO Images(Name, Url) VALUES ('fuck yeah danny trejo','https://images.funplay8.com/test/fuck_yeah_danny_trejo.jpg');
INSERT INTO Images(Name, Url) VALUES ('fuck yeah melvin','https://images.funplay8.com/test/fuck_yeah_melvin.jpg');
INSERT INTO Images(Name, Url) VALUES ('fuck yeah smile','https://images.funplay8.com/test/fuck_yeah_smile.jpg');
INSERT INTO Images(Name, Url) VALUES ('forever alone clean','https://images.funplay8.com/test/forever_alone_clean.jpg');
INSERT INTO Images(Name, Url) VALUES ('forever alone computer','https://images.funplay8.com/test/forever_alone_computer.jpg');
INSERT INTO Images(Name, Url) VALUES ('forever alone face only','https://images.funplay8.com/test/forever_alone_face_only.jpg');
INSERT INTO Images(Name, Url) VALUES ('forever alone happy','https://images.funplay8.com/test/forever_alone_happy.jpg');
INSERT INTO Images(Name, Url) VALUES ('forever alone pirate','https://images.funplay8.com/test/forever_alone_pirate.jpg');
INSERT INTO Images(Name, Url) VALUES ('forever alone sad','https://images.funplay8.com/test/forever_alone_sad.jpg');
INSERT INTO Images(Name, Url) VALUES ('forever alone together','https://images.funplay8.com/test/forever_alone_together.jpg');
INSERT INTO Images(Name, Url) VALUES ('foul bachelor frog','https://images.funplay8.com/test/foul_bachelor_frog.jpg');
INSERT INTO Images(Name, Url) VALUES ('foul bachelorette frog','https://images.funplay8.com/test/foul_bachelorette_frog.jpg');
INSERT INTO Images(Name, Url) VALUES ('fuck you','https://images.funplay8.com/test/fuck_you.jpg');
INSERT INTO Images(Name, Url) VALUES ('fus ro dah','https://images.funplay8.com/test/fus_ro_dah.jpg');
INSERT INTO Images(Name, Url) VALUES ('futurama fry','https://images.funplay8.com/test/futurama_fry.jpg');
INSERT INTO Images(Name, Url) VALUES ('futurama zoidberg','https://images.funplay8.com/test/futurama_zoidberg.jpg');
INSERT INTO Images(Name, Url) VALUES ('fuuu','https://images.funplay8.com/test/fuuu.jpg');
INSERT INTO Images(Name, Url) VALUES ('fuuu karma','https://images.funplay8.com/test/fuuu_karma.jpg');
INSERT INTO Images(Name, Url) VALUES ('gasp','https://images.funplay8.com/test/gasp.jpg');
INSERT INTO Images(Name, Url) VALUES ('gaspcat with glasses','https://images.funplay8.com/test/gaspcat_with_glasses.jpg');
INSERT INTO Images(Name, Url) VALUES ('gay','https://images.funplay8.com/test/gay.jpg');
INSERT INTO Images(Name, Url) VALUES ('genius','https://images.funplay8.com/test/genius.jpg');
INSERT INTO Images(Name, Url) VALUES ('gentleman troll','https://images.funplay8.com/test/gentleman_troll.jpg');
INSERT INTO Images(Name, Url) VALUES ('gentlemen','https://images.funplay8.com/test/gentlemen.jpg');
INSERT INTO Images(Name, Url) VALUES ('glory pc','https://images.funplay8.com/test/glory_pc.jpg');
INSERT INTO Images(Name, Url) VALUES ('go fuck yourself','https://images.funplay8.com/test/go_fuck_yourself.jpg');
INSERT INTO Images(Name, Url) VALUES ('good guy greg','https://images.funplay8.com/test/good_guy_greg.jpg');
INSERT INTO Images(Name, Url) VALUES ('good troll','https://images.funplay8.com/test/good_troll.jpg');
INSERT INTO Images(Name, Url) VALUES ('got a badass','https://images.funplay8.com/test/got_a_badass.jpg');
INSERT INTO Images(Name, Url) VALUES ('got a badass full','https://images.funplay8.com/test/got_a_badass_full.jpg');
INSERT INTO Images(Name, Url) VALUES ('grandma','https://images.funplay8.com/test/grandma.jpg');
INSERT INTO Images(Name, Url) VALUES ('grandma finds the internet','https://images.funplay8.com/test/grandma_finds_the_internet.jpg');
INSERT INTO Images(Name, Url) VALUES ('grin','https://images.funplay8.com/test/grin.jpg');
INSERT INTO Images(Name, Url) VALUES ('grinch','https://images.funplay8.com/test/grinch.jpg');
INSERT INTO Images(Name, Url) VALUES ('gtfo','https://images.funplay8.com/test/gtfo.jpg');
INSERT INTO Images(Name, Url) VALUES ('gtfo clean','https://images.funplay8.com/test/gtfo_clean.jpg');
INSERT INTO Images(Name, Url) VALUES ('gtfo smile','https://images.funplay8.com/test/gtfo_smile.jpg');
INSERT INTO Images(Name, Url) VALUES ('ha','https://images.funplay8.com/test/ha.jpg');
INSERT INTO Images(Name, Url) VALUES ('hah gay','https://images.funplay8.com/test/hah_gay.jpg');
INSERT INTO Images(Name, Url) VALUES ('headphones','https://images.funplay8.com/test/headphones.jpg');
INSERT INTO Images(Name, Url) VALUES ('helpful tyler durden','https://images.funplay8.com/test/helpful_tyler_durden.jpg');
INSERT INTO Images(Name, Url) VALUES ('herp','https://images.funplay8.com/test/herp.jpg');
INSERT INTO Images(Name, Url) VALUES ('herp derp','https://images.funplay8.com/test/herp_derp.jpg');
INSERT INTO Images(Name, Url) VALUES ('hey','https://images.funplay8.com/test/hey.jpg');
INSERT INTO Images(Name, Url) VALUES ('high','https://images.funplay8.com/test/high.jpg');
INSERT INTO Images(Name, Url) VALUES ('high expectations asian father','https://images.funplay8.com/test/high_expectations_asian_father.jpg');
INSERT INTO Images(Name, Url) VALUES ('hipster glasses','https://images.funplay8.com/test/hipster_glasses.jpg');
INSERT INTO Images(Name, Url) VALUES ('hipster kitty','https://images.funplay8.com/test/hipster_kitty.jpg');
INSERT INTO Images(Name, Url) VALUES ('hipsterglasses','https://images.funplay8.com/test/hipsterglasses.jpg');
INSERT INTO Images(Name, Url) VALUES ('hitler','https://images.funplay8.com/test/hitler.jpg');
INSERT INTO Images(Name, Url) VALUES ('hmmm','https://images.funplay8.com/test/hmmm.jpg');
INSERT INTO Images(Name, Url) VALUES ('horror','https://images.funplay8.com/test/horror.jpg');
INSERT INTO Images(Name, Url) VALUES ('hot chick','https://images.funplay8.com/test/hot_chick.jpg');
INSERT INTO Images(Name, Url) VALUES ('huh','https://images.funplay8.com/test/huh.jpg');
INSERT INTO Images(Name, Url) VALUES ('huhm','https://images.funplay8.com/test/huhm.jpg');
INSERT INTO Images(Name, Url) VALUES ('hurrr','https://images.funplay8.com/test/hurrr.jpg');
INSERT INTO Images(Name, Url) VALUES ('hyper troll','https://images.funplay8.com/test/hyper_troll.jpg');
INSERT INTO Images(Name, Url) VALUES ('happy female','https://images.funplay8.com/test/happy_female.jpg');
INSERT INTO Images(Name, Url) VALUES ('happy smile','https://images.funplay8.com/test/happy_smile.jpg');
INSERT INTO Images(Name, Url) VALUES ('happy smoking','https://images.funplay8.com/test/happy_smoking.jpg');
INSERT INTO Images(Name, Url) VALUES ('happy winter','https://images.funplay8.com/test/happy_winter.jpg');
INSERT INTO Images(Name, Url) VALUES ('happy yes','https://images.funplay8.com/test/happy_yes.jpg');
INSERT INTO Images(Name, Url) VALUES ('hat and monocle','https://images.funplay8.com/test/hat_and_monocle.jpg');
INSERT INTO Images(Name, Url) VALUES ('haters gonna hate','https://images.funplay8.com/test/haters_gonna_hate.jpg');
INSERT INTO Images(Name, Url) VALUES ('hawkward','https://images.funplay8.com/test/hawkward.jpg');
INSERT INTO Images(Name, Url) VALUES ('he he','https://images.funplay8.com/test/he_he.jpg');
INSERT INTO Images(Name, Url) VALUES ('i am determined','https://images.funplay8.com/test/i_am_determined.jpg');
INSERT INTO Images(Name, Url) VALUES ('i feels yah','https://images.funplay8.com/test/i_feels_yah.jpg');
INSERT INTO Images(Name, Url) VALUES ('i know what you did there clean','https://images.funplay8.com/test/i_know_what_you_did_there_clean.jpg');
INSERT INTO Images(Name, Url) VALUES ('i lied','https://images.funplay8.com/test/i_lied.jpg');
INSERT INTO Images(Name, Url) VALUES ('i lied black','https://images.funplay8.com/test/i_lied_black.jpg');
INSERT INTO Images(Name, Url) VALUES ('i lied light','https://images.funplay8.com/test/i_lied_light.jpg');
INSERT INTO Images(Name, Url) VALUES ('i regret nothing','https://images.funplay8.com/test/i_regret_nothing.jpg');
INSERT INTO Images(Name, Url) VALUES ('i see what you did there','https://images.funplay8.com/test/i_see_what_you_did_there.jpg');
INSERT INTO Images(Name, Url) VALUES ('i truthed','https://images.funplay8.com/test/i_truthed.jpg');
INSERT INTO Images(Name, Url) VALUES ('inglip gropaga1','https://images.funplay8.com/test/inglip_gropaga1.jpg');
INSERT INTO Images(Name, Url) VALUES ('inglip gropaga2','https://images.funplay8.com/test/inglip_gropaga2.jpg');
INSERT INTO Images(Name, Url) VALUES ('inglip gropaga3','https://images.funplay8.com/test/inglip_gropaga3.jpg');
INSERT INTO Images(Name, Url) VALUES ('inglip gropaga4','https://images.funplay8.com/test/inglip_gropaga4.jpg');
INSERT INTO Images(Name, Url) VALUES ('inglip gropaga5','https://images.funplay8.com/test/inglip_gropaga5.jpg');
INSERT INTO Images(Name, Url) VALUES ('inglip gropaga6','https://images.funplay8.com/test/inglip_gropaga6.jpg');
INSERT INTO Images(Name, Url) VALUES ('inglip gropaga7','https://images.funplay8.com/test/inglip_gropaga7.jpg');
INSERT INTO Images(Name, Url) VALUES ('inglip gropaga amazed','https://images.funplay8.com/test/inglip_gropaga_amazed.jpg');
INSERT INTO Images(Name, Url) VALUES ('inglip gropaga blank','https://images.funplay8.com/test/inglip_gropaga_blank.jpg');
INSERT INTO Images(Name, Url) VALUES ('ich mag gusta','https://images.funplay8.com/test/ich_mag_gusta.jpg');
INSERT INTO Images(Name, Url) VALUES ('if you know what i mean mr bean','https://images.funplay8.com/test/if_you_know_what_i_mean_mr_bean.jpg');
INSERT INTO Images(Name, Url) VALUES ('if you know what i mean mr bean blank','https://images.funplay8.com/test/if_you_know_what_i_mean_mr_bean_blank.jpg');
INSERT INTO Images(Name, Url) VALUES ('im watching u','https://images.funplay8.com/test/im_watching_u.jpg');
INSERT INTO Images(Name, Url) VALUES ('impossibru','https://images.funplay8.com/test/impossibru.jpg');
INSERT INTO Images(Name, Url) VALUES ('indeed','https://images.funplay8.com/test/indeed.jpg');
INSERT INTO Images(Name, Url) VALUES ('inglip','https://images.funplay8.com/test/inglip.jpg');
INSERT INTO Images(Name, Url) VALUES ('inglip full body','https://images.funplay8.com/test/inglip_full_body.jpg');
INSERT INTO Images(Name, Url) VALUES ('inglip full body2','https://images.funplay8.com/test/inglip_full_body2.jpg');
INSERT INTO Images(Name, Url) VALUES ('later 2','https://images.funplay8.com/test/later_2.jpg');
INSERT INTO Images(Name, Url) VALUES ('later that evening','https://images.funplay8.com/test/later_that_evening.jpg');
INSERT INTO Images(Name, Url) VALUES ('lazy college senior','https://images.funplay8.com/test/lazy_college_senior.jpg');
INSERT INTO Images(Name, Url) VALUES ('le fu','https://images.funplay8.com/test/le_fu.jpg');
INSERT INTO Images(Name, Url) VALUES ('lesquee','https://images.funplay8.com/test/lesquee.jpg');
INSERT INTO Images(Name, Url) VALUES ('like a liege','https://images.funplay8.com/test/like_a_liege.jpg');
INSERT INTO Images(Name, Url) VALUES ('like a sir','https://images.funplay8.com/test/like_a_sir.jpg');
INSERT INTO Images(Name, Url) VALUES ('little kid','https://images.funplay8.com/test/little_kid.jpg');
INSERT INTO Images(Name, Url) VALUES ('little longer than a few','https://images.funplay8.com/test/little_longer_than_a_few.jpg');
INSERT INTO Images(Name, Url) VALUES ('its free','https://images.funplay8.com/test/its_free.jpg');
INSERT INTO Images(Name, Url) VALUES ('its not okay','https://images.funplay8.com/test/its_not_okay.jpg');
INSERT INTO Images(Name, Url) VALUES ('its something','https://images.funplay8.com/test/its_something.jpg');
INSERT INTO Images(Name, Url) VALUES ('jackie chan','https://images.funplay8.com/test/jackie_chan.jpg');
INSERT INTO Images(Name, Url) VALUES ('jealous girl','https://images.funplay8.com/test/jealous_girl.jpg');
INSERT INTO Images(Name, Url) VALUES ('jesus','https://images.funplay8.com/test/jesus.jpg');
INSERT INTO Images(Name, Url) VALUES ('jesus dog','https://images.funplay8.com/test/jesus_dog.jpg');
INSERT INTO Images(Name, Url) VALUES ('john cena','https://images.funplay8.com/test/john_cena.jpg');
INSERT INTO Images(Name, Url) VALUES ('joseph ducreux','https://images.funplay8.com/test/joseph_ducreux.jpg');
INSERT INTO Images(Name, Url) VALUES ('lol','https://images.funplay8.com/test/lol.jpg');
INSERT INTO Images(Name, Url) VALUES ('lol crazy','https://images.funplay8.com/test/lol_crazy.jpg');
INSERT INTO Images(Name, Url) VALUES ('long long neck surprise','https://images.funplay8.com/test/long_long_neck_surprise.jpg');
INSERT INTO Images(Name, Url) VALUES ('look from bottom','https://images.funplay8.com/test/look_from_bottom.jpg');
INSERT INTO Images(Name, Url) VALUES ('lovely face','https://images.funplay8.com/test/lovely_face.jpg');
INSERT INTO Images(Name, Url) VALUES ('man crying','https://images.funplay8.com/test/man_crying.jpg');
INSERT INTO Images(Name, Url) VALUES ('me culpa','https://images.funplay8.com/test/me_culpa.jpg');
INSERT INTO Images(Name, Url) VALUES ('me gangsta','https://images.funplay8.com/test/me_gangsta.jpg');
INSERT INTO Images(Name, Url) VALUES ('me gusta','https://images.funplay8.com/test/me_gusta.jpg');
INSERT INTO Images(Name, Url) VALUES ('next day 2','https://images.funplay8.com/test/next_day_2.jpg');
INSERT INTO Images(Name, Url) VALUES ('no','https://images.funplay8.com/test/no.jpg');
INSERT INTO Images(Name, Url) VALUES ('no me gusta','https://images.funplay8.com/test/no_me_gusta.jpg');
INSERT INTO Images(Name, Url) VALUES ('nokia','https://images.funplay8.com/test/nokia.jpg');
INSERT INTO Images(Name, Url) VALUES ('not giving a fuck','https://images.funplay8.com/test/not_giving_a_fuck.jpg');
INSERT INTO Images(Name, Url) VALUES ('not okay smile','https://images.funplay8.com/test/not_okay_smile.jpg');
INSERT INTO Images(Name, Url) VALUES ('not sure if gusta','https://images.funplay8.com/test/not_sure_if_gusta.jpg');
INSERT INTO Images(Name, Url) VALUES ('nothing to do here','https://images.funplay8.com/test/nothing_to_do_here.jpg');
INSERT INTO Images(Name, Url) VALUES ('now kiss','https://images.funplay8.com/test/now_kiss.jpg');
INSERT INTO Images(Name, Url) VALUES ('keyboard break','https://images.funplay8.com/test/keyboard_break.jpg');
INSERT INTO Images(Name, Url) VALUES ('killed a man','https://images.funplay8.com/test/killed_a_man.jpg');
INSERT INTO Images(Name, Url) VALUES ('kitteh smile','https://images.funplay8.com/test/kitteh_smile.jpg');
INSERT INTO Images(Name, Url) VALUES ('knife self','https://images.funplay8.com/test/knife_self.jpg');
INSERT INTO Images(Name, Url) VALUES ('knowthatfeel','https://images.funplay8.com/test/knowthatfeel.jpg');
INSERT INTO Images(Name, Url) VALUES ('koala cant believe','https://images.funplay8.com/test/koala_cant_believe.jpg');
INSERT INTO Images(Name, Url) VALUES ('la di da','https://images.funplay8.com/test/la_di_da.jpg');
INSERT INTO Images(Name, Url) VALUES ('lame pun coon','https://images.funplay8.com/test/lame_pun_coon.jpg');
INSERT INTO Images(Name, Url) VALUES ('later 1','https://images.funplay8.com/test/later_1.jpg');
INSERT INTO Images(Name, Url) VALUES ('inglip gropaga front','https://images.funplay8.com/test/inglip_gropaga_front.jpg');
INSERT INTO Images(Name, Url) VALUES ('inglip gropaga okay','https://images.funplay8.com/test/inglip_gropaga_okay.jpg');
INSERT INTO Images(Name, Url) VALUES ('inglip gropaga why','https://images.funplay8.com/test/inglip_gropaga_why.jpg');
INSERT INTO Images(Name, Url) VALUES ('inglip hail inglip','https://images.funplay8.com/test/inglip_hail_inglip.jpg');
INSERT INTO Images(Name, Url) VALUES ('inglip hood1','https://images.funplay8.com/test/inglip_hood1.jpg');
INSERT INTO Images(Name, Url) VALUES ('inglip hood2','https://images.funplay8.com/test/inglip_hood2.jpg');
INSERT INTO Images(Name, Url) VALUES ('inglip ircip','https://images.funplay8.com/test/inglip_ircip.jpg');
INSERT INTO Images(Name, Url) VALUES ('inglip ready to battle','https://images.funplay8.com/test/inglip_ready_to_battle.jpg');
INSERT INTO Images(Name, Url) VALUES ('insanity wolf','https://images.funplay8.com/test/insanity_wolf.jpg');
INSERT INTO Images(Name, Url) VALUES ('me gusta creepy','https://images.funplay8.com/test/me_gusta_creepy.jpg');
INSERT INTO Images(Name, Url) VALUES ('me gusta makeup','https://images.funplay8.com/test/me_gusta_makeup.jpg');
INSERT INTO Images(Name, Url) VALUES ('me gusta problemo','https://images.funplay8.com/test/me_gusta_problemo.jpg');
INSERT INTO Images(Name, Url) VALUES ('mega rage','https://images.funplay8.com/test/mega_rage.jpg');
INSERT INTO Images(Name, Url) VALUES ('meh cat','https://images.funplay8.com/test/meh_cat.jpg');
INSERT INTO Images(Name, Url) VALUES ('melvin','https://images.funplay8.com/test/melvin.jpg');
INSERT INTO Images(Name, Url) VALUES ('midnight','https://images.funplay8.com/test/midnight.jpg');
INSERT INTO Images(Name, Url) VALUES ('milk','https://images.funplay8.com/test/milk.jpg');
INSERT INTO Images(Name, Url) VALUES ('monocle','https://images.funplay8.com/test/monocle.jpg');
INSERT INTO Images(Name, Url) VALUES ('mother of god','https://images.funplay8.com/test/mother_of_god.jpg');
INSERT INTO Images(Name, Url) VALUES ('mother of god annoyed','https://images.funplay8.com/test/mother_of_god_annoyed.jpg');
INSERT INTO Images(Name, Url) VALUES ('mother of gusta','https://images.funplay8.com/test/mother_of_gusta.jpg');
INSERT INTO Images(Name, Url) VALUES ('mouth wide open','https://images.funplay8.com/test/mouth_wide_open.jpg');
INSERT INTO Images(Name, Url) VALUES ('much later','https://images.funplay8.com/test/much_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('much much later','https://images.funplay8.com/test/much_much_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('much much later 2','https://images.funplay8.com/test/much_much_later_2.jpg');
INSERT INTO Images(Name, Url) VALUES ('much much much later','https://images.funplay8.com/test/much_much_much_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('music shit','https://images.funplay8.com/test/music_shit.jpg');
INSERT INTO Images(Name, Url) VALUES ('musically oblivious 8th grader','https://images.funplay8.com/test/musically_oblivious_8th_grader.jpg');
INSERT INTO Images(Name, Url) VALUES ('must resist','https://images.funplay8.com/test/must_resist.jpg');
INSERT INTO Images(Name, Url) VALUES ('nerd','https://images.funplay8.com/test/nerd.jpg');
INSERT INTO Images(Name, Url) VALUES ('nerd rainbow puke','https://images.funplay8.com/test/nerd_rainbow_puke.jpg');
INSERT INTO Images(Name, Url) VALUES ('net noob','https://images.funplay8.com/test/net_noob.jpg');
INSERT INTO Images(Name, Url) VALUES ('never alone','https://images.funplay8.com/test/never_alone.jpg');
INSERT INTO Images(Name, Url) VALUES ('newspaper guy','https://images.funplay8.com/test/newspaper_guy.jpg');
INSERT INTO Images(Name, Url) VALUES ('newspaper guy tear','https://images.funplay8.com/test/newspaper_guy_tear.jpg');
INSERT INTO Images(Name, Url) VALUES ('next day','https://images.funplay8.com/test/next_day.jpg');
INSERT INTO Images(Name, Url) VALUES ('nuclear rage','https://images.funplay8.com/test/nuclear_rage.jpg');
INSERT INTO Images(Name, Url) VALUES ('numb','https://images.funplay8.com/test/numb.jpg');
INSERT INTO Images(Name, Url) VALUES ('obama michelle not bad','https://images.funplay8.com/test/obama_michelle_not_bad.jpg');
INSERT INTO Images(Name, Url) VALUES ('obama not bad','https://images.funplay8.com/test/obama_not_bad.jpg');
INSERT INTO Images(Name, Url) VALUES ('objection','https://images.funplay8.com/test/objection.jpg');
INSERT INTO Images(Name, Url) VALUES ('oh','https://images.funplay8.com/test/oh.jpg');
INSERT INTO Images(Name, Url) VALUES ('oh god','https://images.funplay8.com/test/oh_god.jpg');
INSERT INTO Images(Name, Url) VALUES ('oh god why','https://images.funplay8.com/test/oh_god_why.jpg');
INSERT INTO Images(Name, Url) VALUES ('oh my goodness','https://images.funplay8.com/test/oh_my_goodness.jpg');
INSERT INTO Images(Name, Url) VALUES ('pokerface clean','https://images.funplay8.com/test/pokerface_clean.jpg');
INSERT INTO Images(Name, Url) VALUES ('portal rainbows','https://images.funplay8.com/test/portal_rainbows.jpg');
INSERT INTO Images(Name, Url) VALUES ('possibru','https://images.funplay8.com/test/possibru.jpg');
INSERT INTO Images(Name, Url) VALUES ('pretty badass','https://images.funplay8.com/test/pretty_badass.jpg');
INSERT INTO Images(Name, Url) VALUES ('problem guy','https://images.funplay8.com/test/problem_guy.jpg');
INSERT INTO Images(Name, Url) VALUES ('problemo','https://images.funplay8.com/test/problemo.jpg');
INSERT INTO Images(Name, Url) VALUES ('provincial man','https://images.funplay8.com/test/provincial_man.jpg');
INSERT INTO Images(Name, Url) VALUES ('psssyeah','https://images.funplay8.com/test/psssyeah.jpg');
INSERT INTO Images(Name, Url) VALUES ('questioning','https://images.funplay8.com/test/questioning.jpg');
INSERT INTO Images(Name, Url) VALUES ('oh no','https://images.funplay8.com/test/oh_no.jpg');
INSERT INTO Images(Name, Url) VALUES ('oh shit','https://images.funplay8.com/test/oh_shit.jpg');
INSERT INTO Images(Name, Url) VALUES ('oh you','https://images.funplay8.com/test/oh_you.jpg');
INSERT INTO Images(Name, Url) VALUES ('oh you so cute','https://images.funplay8.com/test/oh_you_so_cute.jpg');
INSERT INTO Images(Name, Url) VALUES ('ohhh yes','https://images.funplay8.com/test/ohhh_yes.jpg');
INSERT INTO Images(Name, Url) VALUES ('ohhh yes front','https://images.funplay8.com/test/ohhh_yes_front.jpg');
INSERT INTO Images(Name, Url) VALUES ('ohhhla','https://images.funplay8.com/test/ohhhla.jpg');
INSERT INTO Images(Name, Url) VALUES ('okay clean','https://images.funplay8.com/test/okay_clean.jpg');
INSERT INTO Images(Name, Url) VALUES ('okay gusta','https://images.funplay8.com/test/okay_gusta.jpg');
INSERT INTO Images(Name, Url) VALUES ('okay guy','https://images.funplay8.com/test/okay_guy.jpg');
INSERT INTO Images(Name, Url) VALUES ('okay guy backgrounded','https://images.funplay8.com/test/okay_guy_backgrounded.jpg');
INSERT INTO Images(Name, Url) VALUES ('okay guy no','https://images.funplay8.com/test/okay_guy_no.jpg');
INSERT INTO Images(Name, Url) VALUES ('okay pfftch','https://images.funplay8.com/test/okay_pfftch.jpg');
INSERT INTO Images(Name, Url) VALUES ('omega rage','https://images.funplay8.com/test/omega_rage.jpg');
INSERT INTO Images(Name, Url) VALUES ('omega troll','https://images.funplay8.com/test/omega_troll.jpg');
INSERT INTO Images(Name, Url) VALUES ('omg run','https://images.funplay8.com/test/omg_run.jpg');
INSERT INTO Images(Name, Url) VALUES ('one does not simply','https://images.funplay8.com/test/one_does_not_simply.jpg');
INSERT INTO Images(Name, Url) VALUES ('one eternity later','https://images.funplay8.com/test/one_eternity_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('one hour later','https://images.funplay8.com/test/one_hour_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('one week later','https://images.funplay8.com/test/one_week_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('ordinary muslim man','https://images.funplay8.com/test/ordinary_muslim_man.jpg');
INSERT INTO Images(Name, Url) VALUES ('original rage','https://images.funplay8.com/test/original_rage.jpg');
INSERT INTO Images(Name, Url) VALUES ('paranoid parrot','https://images.funplay8.com/test/paranoid_parrot.jpg');
INSERT INTO Images(Name, Url) VALUES ('pedobear','https://images.funplay8.com/test/pedobear.jpg');
INSERT INTO Images(Name, Url) VALUES ('pedobear backgrounded','https://images.funplay8.com/test/pedobear_backgrounded.jpg');
INSERT INTO Images(Name, Url) VALUES ('pedobear coming','https://images.funplay8.com/test/pedobear_coming.jpg');
INSERT INTO Images(Name, Url) VALUES ('pfffftch 2','https://images.funplay8.com/test/pfffftch_2.jpg');
INSERT INTO Images(Name, Url) VALUES ('red big smile','https://images.funplay8.com/test/red_big_smile.jpg');
INSERT INTO Images(Name, Url) VALUES ('red concentrated','https://images.funplay8.com/test/red_concentrated.jpg');
INSERT INTO Images(Name, Url) VALUES ('red crying','https://images.funplay8.com/test/red_crying.jpg');
INSERT INTO Images(Name, Url) VALUES ('red dazed','https://images.funplay8.com/test/red_dazed.jpg');
INSERT INTO Images(Name, Url) VALUES ('red determined','https://images.funplay8.com/test/red_determined.jpg');
INSERT INTO Images(Name, Url) VALUES ('red dude','https://images.funplay8.com/test/red_dude.jpg');
INSERT INTO Images(Name, Url) VALUES ('red dumbfounded','https://images.funplay8.com/test/red_dumbfounded.jpg');
INSERT INTO Images(Name, Url) VALUES ('red ewbte','https://images.funplay8.com/test/red_ewbte.jpg');
INSERT INTO Images(Name, Url) VALUES ('red excited','https://images.funplay8.com/test/red_excited.jpg');
INSERT INTO Images(Name, Url) VALUES ('pfffftch 3','https://images.funplay8.com/test/pfffftch_3.jpg');
INSERT INTO Images(Name, Url) VALUES ('pfffrrr','https://images.funplay8.com/test/pfffrrr.jpg');
INSERT INTO Images(Name, Url) VALUES ('pfftch','https://images.funplay8.com/test/pfftch.jpg');
INSERT INTO Images(Name, Url) VALUES ('pfftttch','https://images.funplay8.com/test/pfftttch.jpg');
INSERT INTO Images(Name, Url) VALUES ('philosoraptor','https://images.funplay8.com/test/philosoraptor.jpg');
INSERT INTO Images(Name, Url) VALUES ('photogenic guy','https://images.funplay8.com/test/photogenic_guy.jpg');
INSERT INTO Images(Name, Url) VALUES ('pick up boy','https://images.funplay8.com/test/pick_up_boy.jpg');
INSERT INTO Images(Name, Url) VALUES ('pick up boy 2','https://images.funplay8.com/test/pick_up_boy_2.jpg');
INSERT INTO Images(Name, Url) VALUES ('pick up boy strikes','https://images.funplay8.com/test/pick_up_boy_strikes.jpg');
INSERT INTO Images(Name, Url) VALUES ('pick up boy with girl','https://images.funplay8.com/test/pick_up_boy_with_girl.jpg');
INSERT INTO Images(Name, Url) VALUES ('pickup line panda','https://images.funplay8.com/test/pickup_line_panda.jpg');
INSERT INTO Images(Name, Url) VALUES ('pig rage','https://images.funplay8.com/test/pig_rage.jpg');
INSERT INTO Images(Name, Url) VALUES ('pirate','https://images.funplay8.com/test/pirate.jpg');
INSERT INTO Images(Name, Url) VALUES ('pleaseguy','https://images.funplay8.com/test/pleaseguy.jpg');
INSERT INTO Images(Name, Url) VALUES ('poker face 3','https://images.funplay8.com/test/poker_face_3.jpg');
INSERT INTO Images(Name, Url) VALUES ('pokerface','https://images.funplay8.com/test/pokerface.jpg');
INSERT INTO Images(Name, Url) VALUES ('pokerface 2','https://images.funplay8.com/test/pokerface_2.jpg');
INSERT INTO Images(Name, Url) VALUES ('pokerface 2 clean','https://images.funplay8.com/test/pokerface_2_clean.jpg');
INSERT INTO Images(Name, Url) VALUES ('red gasp2','https://images.funplay8.com/test/red_gasp2.jpg');
INSERT INTO Images(Name, Url) VALUES ('red happy','https://images.funplay8.com/test/red_happy.jpg');
INSERT INTO Images(Name, Url) VALUES ('red hmmm','https://images.funplay8.com/test/red_hmmm.jpg');
INSERT INTO Images(Name, Url) VALUES ('red i wonder','https://images.funplay8.com/test/red_i_wonder.jpg');
INSERT INTO Images(Name, Url) VALUES ('red ladystare','https://images.funplay8.com/test/red_ladystare.jpg');
INSERT INTO Images(Name, Url) VALUES ('red ladystare2','https://images.funplay8.com/test/red_ladystare2.jpg');
INSERT INTO Images(Name, Url) VALUES ('red lean','https://images.funplay8.com/test/red_lean.jpg');
INSERT INTO Images(Name, Url) VALUES ('red lol','https://images.funplay8.com/test/red_lol.jpg');
INSERT INTO Images(Name, Url) VALUES ('red me gusta','https://images.funplay8.com/test/red_me_gusta.jpg');
INSERT INTO Images(Name, Url) VALUES ('quiet rage','https://images.funplay8.com/test/quiet_rage.jpg');
INSERT INTO Images(Name, Url) VALUES ('rage cat','https://images.funplay8.com/test/rage_cat.jpg');
INSERT INTO Images(Name, Url) VALUES ('rage eyes','https://images.funplay8.com/test/rage_eyes.jpg');
INSERT INTO Images(Name, Url) VALUES ('rage fu','https://images.funplay8.com/test/rage_fu.jpg');
INSERT INTO Images(Name, Url) VALUES ('rainbow out the eyes','https://images.funplay8.com/test/rainbow_out_the_eyes.jpg');
INSERT INTO Images(Name, Url) VALUES ('rainbow puke','https://images.funplay8.com/test/rainbow_puke.jpg');
INSERT INTO Images(Name, Url) VALUES ('reaction guy','https://images.funplay8.com/test/reaction_guy.jpg');
INSERT INTO Images(Name, Url) VALUES ('real life','https://images.funplay8.com/test/real_life.jpg');
INSERT INTO Images(Name, Url) VALUES ('realism troll','https://images.funplay8.com/test/realism_troll.jpg');
INSERT INTO Images(Name, Url) VALUES ('red excited bliss','https://images.funplay8.com/test/red_excited_bliss.jpg');
INSERT INTO Images(Name, Url) VALUES ('red excited tears','https://images.funplay8.com/test/red_excited_tears.jpg');
INSERT INTO Images(Name, Url) VALUES ('red facepalm','https://images.funplay8.com/test/red_facepalm.jpg');
INSERT INTO Images(Name, Url) VALUES ('red fake smile','https://images.funplay8.com/test/red_fake_smile.jpg');
INSERT INTO Images(Name, Url) VALUES ('red forever alone','https://images.funplay8.com/test/red_forever_alone.jpg');
INSERT INTO Images(Name, Url) VALUES ('red freddie','https://images.funplay8.com/test/red_freddie.jpg');
INSERT INTO Images(Name, Url) VALUES ('red fuck that bitch','https://images.funplay8.com/test/red_fuck_that_bitch.jpg');
INSERT INTO Images(Name, Url) VALUES ('red fuck yeah','https://images.funplay8.com/test/red_fuck_yeah.jpg');
INSERT INTO Images(Name, Url) VALUES ('red gasp','https://images.funplay8.com/test/red_gasp.jpg');
INSERT INTO Images(Name, Url) VALUES ('red milk','https://images.funplay8.com/test/red_milk.jpg');
INSERT INTO Images(Name, Url) VALUES ('red normal','https://images.funplay8.com/test/red_normal.jpg');
INSERT INTO Images(Name, Url) VALUES ('red normal2','https://images.funplay8.com/test/red_normal2.jpg');
INSERT INTO Images(Name, Url) VALUES ('red okay','https://images.funplay8.com/test/red_okay.jpg');
INSERT INTO Images(Name, Url) VALUES ('red omgrun','https://images.funplay8.com/test/red_omgrun.jpg');
INSERT INTO Images(Name, Url) VALUES ('red pfft','https://images.funplay8.com/test/red_pfft.jpg');
INSERT INTO Images(Name, Url) VALUES ('red quite','https://images.funplay8.com/test/red_quite.jpg');
INSERT INTO Images(Name, Url) VALUES ('red rage','https://images.funplay8.com/test/red_rage.jpg');
INSERT INTO Images(Name, Url) VALUES ('red rage2','https://images.funplay8.com/test/red_rage2.jpg');
INSERT INTO Images(Name, Url) VALUES ('red rage canadian','https://images.funplay8.com/test/red_rage_canadian.jpg');
INSERT INTO Images(Name, Url) VALUES ('red rage extreme','https://images.funplay8.com/test/red_rage_extreme.jpg');
INSERT INTO Images(Name, Url) VALUES ('red rage extreme2','https://images.funplay8.com/test/red_rage_extreme2.jpg');
INSERT INTO Images(Name, Url) VALUES ('red rage foaming','https://images.funplay8.com/test/red_rage_foaming.jpg');
INSERT INTO Images(Name, Url) VALUES ('red rage getting pissed','https://images.funplay8.com/test/red_rage_getting_pissed.jpg');
INSERT INTO Images(Name, Url) VALUES ('red rage mad','https://images.funplay8.com/test/red_rage_mad.jpg');
INSERT INTO Images(Name, Url) VALUES ('red rage mad2','https://images.funplay8.com/test/red_rage_mad2.jpg');
INSERT INTO Images(Name, Url) VALUES ('red rage quiet','https://images.funplay8.com/test/red_rage_quiet.jpg');
INSERT INTO Images(Name, Url) VALUES ('red rage shaking','https://images.funplay8.com/test/red_rage_shaking.jpg');
INSERT INTO Images(Name, Url) VALUES ('red rage super','https://images.funplay8.com/test/red_rage_super.jpg');
INSERT INTO Images(Name, Url) VALUES ('red really determined','https://images.funplay8.com/test/red_really_determined.jpg');
INSERT INTO Images(Name, Url) VALUES ('red red tongue','https://images.funplay8.com/test/red_red_tongue.jpg');
INSERT INTO Images(Name, Url) VALUES ('red schlick','https://images.funplay8.com/test/red_schlick.jpg');
INSERT INTO Images(Name, Url) VALUES ('red smile','https://images.funplay8.com/test/red_smile.jpg');
INSERT INTO Images(Name, Url) VALUES ('red sweet tears','https://images.funplay8.com/test/red_sweet_tears.jpg');
INSERT INTO Images(Name, Url) VALUES ('red tongue','https://images.funplay8.com/test/red_tongue.jpg');
INSERT INTO Images(Name, Url) VALUES ('red tongue down','https://images.funplay8.com/test/red_tongue_down.jpg');
INSERT INTO Images(Name, Url) VALUES ('red troll','https://images.funplay8.com/test/red_troll.jpg');
INSERT INTO Images(Name, Url) VALUES ('red troll sad','https://images.funplay8.com/test/red_troll_sad.jpg');
INSERT INTO Images(Name, Url) VALUES ('red what','https://images.funplay8.com/test/red_what.jpg');
INSERT INTO Images(Name, Url) VALUES ('red why','https://images.funplay8.com/test/red_why.jpg');
INSERT INTO Images(Name, Url) VALUES ('red why no hands','https://images.funplay8.com/test/red_why_no_hands.jpg');
INSERT INTO Images(Name, Url) VALUES ('red wut','https://images.funplay8.com/test/red_wut.jpg');
INSERT INTO Images(Name, Url) VALUES ('redditors wife','https://images.funplay8.com/test/redditors_wife.jpg');
INSERT INTO Images(Name, Url) VALUES ('redhair','https://images.funplay8.com/test/redhair.jpg');
INSERT INTO Images(Name, Url) VALUES ('redneck randal','https://images.funplay8.com/test/redneck_randal.jpg');
INSERT INTO Images(Name, Url) VALUES ('ridiciously photogenic metalhead','https://images.funplay8.com/test/ridiciously_photogenic_metalhead.jpg');
INSERT INTO Images(Name, Url) VALUES ('rly clean everything','https://images.funplay8.com/test/rly_clean_everything.jpg');
INSERT INTO Images(Name, Url) VALUES ('royal wedding girl','https://images.funplay8.com/test/royal_wedding_girl.jpg');
INSERT INTO Images(Name, Url) VALUES ('sad','https://images.funplay8.com/test/sad.jpg');
INSERT INTO Images(Name, Url) VALUES ('sad computer','https://images.funplay8.com/test/sad_computer.jpg');
INSERT INTO Images(Name, Url) VALUES ('sad melvin','https://images.funplay8.com/test/sad_melvin.jpg');
INSERT INTO Images(Name, Url) VALUES ('sad shadow','https://images.funplay8.com/test/sad_shadow.jpg');
INSERT INTO Images(Name, Url) VALUES ('sad sitting','https://images.funplay8.com/test/sad_sitting.jpg');
INSERT INTO Images(Name, Url) VALUES ('sad troll face','https://images.funplay8.com/test/sad_troll_face.jpg');
INSERT INTO Images(Name, Url) VALUES ('sad why','https://images.funplay8.com/test/sad_why.jpg');
INSERT INTO Images(Name, Url) VALUES ('sexual frustration','https://images.funplay8.com/test/sexual_frustration.jpg');
INSERT INTO Images(Name, Url) VALUES ('sexually oblivious rhino','https://images.funplay8.com/test/sexually_oblivious_rhino.jpg');
INSERT INTO Images(Name, Url) VALUES ('sheltering suburban mom','https://images.funplay8.com/test/sheltering_suburban_mom.jpg');
INSERT INTO Images(Name, Url) VALUES ('shocked','https://images.funplay8.com/test/shocked.jpg');
INSERT INTO Images(Name, Url) VALUES ('shrug','https://images.funplay8.com/test/shrug.jpg');
INSERT INTO Images(Name, Url) VALUES ('side mouth','https://images.funplay8.com/test/side_mouth.jpg');
INSERT INTO Images(Name, Url) VALUES ('sincere troll','https://images.funplay8.com/test/sincere_troll.jpg');
INSERT INTO Images(Name, Url) VALUES ('six hours later','https://images.funplay8.com/test/six_hours_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('six hours later 2','https://images.funplay8.com/test/six_hours_later_2.jpg');
INSERT INTO Images(Name, Url) VALUES ('sarcasm','https://images.funplay8.com/test/sarcasm.jpg');
INSERT INTO Images(Name, Url) VALUES ('scared yao','https://images.funplay8.com/test/scared_yao.jpg');
INSERT INTO Images(Name, Url) VALUES ('scroll scroll','https://images.funplay8.com/test/scroll_scroll.jpg');
INSERT INTO Images(Name, Url) VALUES ('scumbag brain','https://images.funplay8.com/test/scumbag_brain.jpg');
INSERT INTO Images(Name, Url) VALUES ('scumbag cap','https://images.funplay8.com/test/scumbag_cap.jpg');
INSERT INTO Images(Name, Url) VALUES ('scumbag steve','https://images.funplay8.com/test/scumbag_steve.jpg');
INSERT INTO Images(Name, Url) VALUES ('serious not okay','https://images.funplay8.com/test/serious_not_okay.jpg');
INSERT INTO Images(Name, Url) VALUES ('seriously','https://images.funplay8.com/test/seriously.jpg');
INSERT INTO Images(Name, Url) VALUES ('several days later','https://images.funplay8.com/test/several_days_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('surprised rage clean','https://images.funplay8.com/test/surprised_rage_clean.jpg');
INSERT INTO Images(Name, Url) VALUES ('surprised wait','https://images.funplay8.com/test/surprised_wait.jpg');
INSERT INTO Images(Name, Url) VALUES ('surprised wide open','https://images.funplay8.com/test/surprised_wide_open.jpg');
INSERT INTO Images(Name, Url) VALUES ('suspicious','https://images.funplay8.com/test/suspicious.jpg');
INSERT INTO Images(Name, Url) VALUES ('sweaty concentrated','https://images.funplay8.com/test/sweaty_concentrated.jpg');
INSERT INTO Images(Name, Url) VALUES ('sweet jesus eyes hanging out','https://images.funplay8.com/test/sweet_jesus_eyes_hanging_out.jpg');
INSERT INTO Images(Name, Url) VALUES ('sweet jesus face','https://images.funplay8.com/test/sweet_jesus_face.jpg');
INSERT INTO Images(Name, Url) VALUES ('tears in the eyes','https://images.funplay8.com/test/tears_in_the_eyes.jpg');
INSERT INTO Images(Name, Url) VALUES ('tech impaired duck','https://images.funplay8.com/test/tech_impaired_duck.jpg');
INSERT INTO Images(Name, Url) VALUES ('slowpoke','https://images.funplay8.com/test/slowpoke.jpg');
INSERT INTO Images(Name, Url) VALUES ('smashing','https://images.funplay8.com/test/smashing.jpg');
INSERT INTO Images(Name, Url) VALUES ('so close freddie mercury','https://images.funplay8.com/test/so_close_freddie_mercury.jpg');
INSERT INTO Images(Name, Url) VALUES ('so hardcore','https://images.funplay8.com/test/so_hardcore.jpg');
INSERT INTO Images(Name, Url) VALUES ('so much win','https://images.funplay8.com/test/so_much_win.jpg');
INSERT INTO Images(Name, Url) VALUES ('so there','https://images.funplay8.com/test/so_there.jpg');
INSERT INTO Images(Name, Url) VALUES ('so there close','https://images.funplay8.com/test/so_there_close.jpg');
INSERT INTO Images(Name, Url) VALUES ('socially awesome penguin','https://images.funplay8.com/test/socially_awesome_penguin.jpg');
INSERT INTO Images(Name, Url) VALUES ('socially awkward penguin','https://images.funplay8.com/test/socially_awkward_penguin.jpg');
INSERT INTO Images(Name, Url) VALUES ('something to do here','https://images.funplay8.com/test/something_to_do_here.jpg');
INSERT INTO Images(Name, Url) VALUES ('son i am disappoint','https://images.funplay8.com/test/son_i_am_disappoint.jpg');
INSERT INTO Images(Name, Url) VALUES ('speech','https://images.funplay8.com/test/speech.jpg');
INSERT INTO Images(Name, Url) VALUES ('speech2','https://images.funplay8.com/test/speech2.jpg');
INSERT INTO Images(Name, Url) VALUES ('speech3','https://images.funplay8.com/test/speech3.jpg');
INSERT INTO Images(Name, Url) VALUES ('speech4','https://images.funplay8.com/test/speech4.jpg');
INSERT INTO Images(Name, Url) VALUES ('speech5','https://images.funplay8.com/test/speech5.jpg');
INSERT INTO Images(Name, Url) VALUES ('speech6','https://images.funplay8.com/test/speech6.jpg');
INSERT INTO Images(Name, Url) VALUES ('spiderpman','https://images.funplay8.com/test/spiderpman.jpg');
INSERT INTO Images(Name, Url) VALUES ('steamboat troll','https://images.funplay8.com/test/steamboat_troll.jpg');
INSERT INTO Images(Name, Url) VALUES ('stoned what','https://images.funplay8.com/test/stoned_what.jpg');
INSERT INTO Images(Name, Url) VALUES ('stoner dog','https://images.funplay8.com/test/stoner_dog.jpg');
INSERT INTO Images(Name, Url) VALUES ('stop it','https://images.funplay8.com/test/stop_it.jpg');
INSERT INTO Images(Name, Url) VALUES ('stop it angry','https://images.funplay8.com/test/stop_it_angry.jpg');
INSERT INTO Images(Name, Url) VALUES ('success','https://images.funplay8.com/test/success.jpg');
INSERT INTO Images(Name, Url) VALUES ('success kid','https://images.funplay8.com/test/success_kid.jpg');
INSERT INTO Images(Name, Url) VALUES ('successful black man','https://images.funplay8.com/test/successful_black_man.jpg');
INSERT INTO Images(Name, Url) VALUES ('sunny student','https://images.funplay8.com/test/sunny_student.jpg');
INSERT INTO Images(Name, Url) VALUES ('super rage','https://images.funplay8.com/test/super_rage.jpg');
INSERT INTO Images(Name, Url) VALUES ('surprised Commissar','https://images.funplay8.com/test/surprised_Commissar.jpg');
INSERT INTO Images(Name, Url) VALUES ('surprised gasp','https://images.funplay8.com/test/surprised_gasp.jpg');
INSERT INTO Images(Name, Url) VALUES ('surprised great scott','https://images.funplay8.com/test/surprised_great_scott.jpg');
INSERT INTO Images(Name, Url) VALUES ('surprised kid','https://images.funplay8.com/test/surprised_kid.jpg');
INSERT INTO Images(Name, Url) VALUES ('surprised long neck surprise','https://images.funplay8.com/test/surprised_long_neck_surprise.jpg');
INSERT INTO Images(Name, Url) VALUES ('surprised mother of god','https://images.funplay8.com/test/surprised_mother_of_god.jpg');
INSERT INTO Images(Name, Url) VALUES ('surprised oh fuck no','https://images.funplay8.com/test/surprised_oh_fuck_no.jpg');
INSERT INTO Images(Name, Url) VALUES ('surprised open mouth','https://images.funplay8.com/test/surprised_open_mouth.jpg');
INSERT INTO Images(Name, Url) VALUES ('thanks','https://images.funplay8.com/test/thanks.jpg');
INSERT INTO Images(Name, Url) VALUES ('that is suspicious','https://images.funplay8.com/test/that_is_suspicious.jpg');
INSERT INTO Images(Name, Url) VALUES ('the most interesting cat in the world','https://images.funplay8.com/test/the_most_interesting_cat_in_the_world.jpg');
INSERT INTO Images(Name, Url) VALUES ('the most interesting man in the world','https://images.funplay8.com/test/the_most_interesting_man_in_the_world.jpg');
INSERT INTO Images(Name, Url) VALUES ('things went okay','https://images.funplay8.com/test/things_went_okay.jpg');
INSERT INTO Images(Name, Url) VALUES ('third world success','https://images.funplay8.com/test/third_world_success.jpg');
INSERT INTO Images(Name, Url) VALUES ('this is awkward','https://images.funplay8.com/test/this_is_awkward.jpg');
INSERT INTO Images(Name, Url) VALUES ('thousands of tears later','https://images.funplay8.com/test/thousands_of_tears_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('three hours later','https://images.funplay8.com/test/three_hours_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('three hours later 2','https://images.funplay8.com/test/three_hours_later_2.jpg');
INSERT INTO Images(Name, Url) VALUES ('three weeks later','https://images.funplay8.com/test/three_weeks_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('three weeks later 2','https://images.funplay8.com/test/three_weeks_later_2.jpg');
INSERT INTO Images(Name, Url) VALUES ('thumbs up','https://images.funplay8.com/test/thumbs_up.jpg');
INSERT INTO Images(Name, Url) VALUES ('today is monday','https://images.funplay8.com/test/today_is_monday.jpg');
INSERT INTO Images(Name, Url) VALUES ('toker face','https://images.funplay8.com/test/toker_face.jpg');
INSERT INTO Images(Name, Url) VALUES ('tomorrow','https://images.funplay8.com/test/tomorrow.jpg');
INSERT INTO Images(Name, Url) VALUES ('tomorrow for sure','https://images.funplay8.com/test/tomorrow_for_sure.jpg');
INSERT INTO Images(Name, Url) VALUES ('trees','https://images.funplay8.com/test/trees.jpg');
INSERT INTO Images(Name, Url) VALUES ('two hours later 2','https://images.funplay8.com/test/two_hours_later_2.jpg');
INSERT INTO Images(Name, Url) VALUES ('two hours later 3','https://images.funplay8.com/test/two_hours_later_3.jpg');
INSERT INTO Images(Name, Url) VALUES ('two hours later 4','https://images.funplay8.com/test/two_hours_later_4.jpg');
INSERT INTO Images(Name, Url) VALUES ('two hours later 5','https://images.funplay8.com/test/two_hours_later_5.jpg');
INSERT INTO Images(Name, Url) VALUES ('u jelly','https://images.funplay8.com/test/u_jelly.jpg');
INSERT INTO Images(Name, Url) VALUES ('ultra gay','https://images.funplay8.com/test/ultra_gay.jpg');
INSERT INTO Images(Name, Url) VALUES ('unhappy','https://images.funplay8.com/test/unhappy.jpg');
INSERT INTO Images(Name, Url) VALUES ('wait','https://images.funplay8.com/test/wait.jpg');
INSERT INTO Images(Name, Url) VALUES ('wait no','https://images.funplay8.com/test/wait_no.jpg');
INSERT INTO Images(Name, Url) VALUES ('trees angry','https://images.funplay8.com/test/trees_angry.jpg');
INSERT INTO Images(Name, Url) VALUES ('trees big mouth','https://images.funplay8.com/test/trees_big_mouth.jpg');
INSERT INTO Images(Name, Url) VALUES ('trees confused','https://images.funplay8.com/test/trees_confused.jpg');
INSERT INTO Images(Name, Url) VALUES ('trees happy','https://images.funplay8.com/test/trees_happy.jpg');
INSERT INTO Images(Name, Url) VALUES ('trees small mouth','https://images.funplay8.com/test/trees_small_mouth.jpg');
INSERT INTO Images(Name, Url) VALUES ('trees smile','https://images.funplay8.com/test/trees_smile.jpg');
INSERT INTO Images(Name, Url) VALUES ('trees stoned','https://images.funplay8.com/test/trees_stoned.jpg');
INSERT INTO Images(Name, Url) VALUES ('trees stoned exhale','https://images.funplay8.com/test/trees_stoned_exhale.jpg');
INSERT INTO Images(Name, Url) VALUES ('trees stoned inhale','https://images.funplay8.com/test/trees_stoned_inhale.jpg');
INSERT INTO Images(Name, Url) VALUES ('wat','https://images.funplay8.com/test/wat.jpg');
INSERT INTO Images(Name, Url) VALUES ('wha','https://images.funplay8.com/test/wha.jpg');
INSERT INTO Images(Name, Url) VALUES ('what','https://images.funplay8.com/test/what.jpg');
INSERT INTO Images(Name, Url) VALUES ('what have you done','https://images.funplay8.com/test/what_have_you_done.jpg');
INSERT INTO Images(Name, Url) VALUES ('what this badass shit means','https://images.funplay8.com/test/what_this_badass_shit_means.jpg');
INSERT INTO Images(Name, Url) VALUES ('why boy','https://images.funplay8.com/test/why_boy.jpg');
INSERT INTO Images(Name, Url) VALUES ('whyyy','https://images.funplay8.com/test/whyyy.jpg');
INSERT INTO Images(Name, Url) VALUES ('whyyy backgrounded','https://images.funplay8.com/test/whyyy_backgrounded.jpg');
INSERT INTO Images(Name, Url) VALUES ('will smith','https://images.funplay8.com/test/will_smith.jpg');
INSERT INTO Images(Name, Url) VALUES ('trex rage','https://images.funplay8.com/test/trex_rage.jpg');
INSERT INTO Images(Name, Url) VALUES ('troll 2','https://images.funplay8.com/test/troll_2.jpg');
INSERT INTO Images(Name, Url) VALUES ('troll badumts','https://images.funplay8.com/test/troll_badumts.jpg');
INSERT INTO Images(Name, Url) VALUES ('troll ballon','https://images.funplay8.com/test/troll_ballon.jpg');
INSERT INTO Images(Name, Url) VALUES ('troll black','https://images.funplay8.com/test/troll_black.jpg');
INSERT INTO Images(Name, Url) VALUES ('troll black beaten','https://images.funplay8.com/test/troll_black_beaten.jpg');
INSERT INTO Images(Name, Url) VALUES ('troll crazy','https://images.funplay8.com/test/troll_crazy.jpg');
INSERT INTO Images(Name, Url) VALUES ('troll dad','https://images.funplay8.com/test/troll_dad.jpg');
INSERT INTO Images(Name, Url) VALUES ('troll dad dance','https://images.funplay8.com/test/troll_dad_dance.jpg');
INSERT INTO Images(Name, Url) VALUES ('troll dad full','https://images.funplay8.com/test/troll_dad_full.jpg');
INSERT INTO Images(Name, Url) VALUES ('troll dad monocle','https://images.funplay8.com/test/troll_dad_monocle.jpg');
INSERT INTO Images(Name, Url) VALUES ('troll face','https://images.funplay8.com/test/troll_face.jpg');
INSERT INTO Images(Name, Url) VALUES ('troll face backgrounded','https://images.funplay8.com/test/troll_face_backgrounded.jpg');
INSERT INTO Images(Name, Url) VALUES ('troll full','https://images.funplay8.com/test/troll_full.jpg');
INSERT INTO Images(Name, Url) VALUES ('troll granny','https://images.funplay8.com/test/troll_granny.jpg');
INSERT INTO Images(Name, Url) VALUES ('troll gusta','https://images.funplay8.com/test/troll_gusta.jpg');
INSERT INTO Images(Name, Url) VALUES ('troll mickey','https://images.funplay8.com/test/troll_mickey.jpg');
INSERT INTO Images(Name, Url) VALUES ('troll problem','https://images.funplay8.com/test/troll_problem.jpg');
INSERT INTO Images(Name, Url) VALUES ('troll typing','https://images.funplay8.com/test/troll_typing.jpg');
INSERT INTO Images(Name, Url) VALUES ('trollol','https://images.funplay8.com/test/trollol.jpg');
INSERT INTO Images(Name, Url) VALUES ('trologirl','https://images.funplay8.com/test/trologirl.jpg');
INSERT INTO Images(Name, Url) VALUES ('true fucking story','https://images.funplay8.com/test/true_fucking_story.jpg');
INSERT INTO Images(Name, Url) VALUES ('true story','https://images.funplay8.com/test/true_story.jpg');
INSERT INTO Images(Name, Url) VALUES ('trumpet','https://images.funplay8.com/test/trumpet.jpg');
INSERT INTO Images(Name, Url) VALUES ('twenty minutes later','https://images.funplay8.com/test/twenty_minutes_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('two boring minutes','https://images.funplay8.com/test/two_boring_minutes.jpg');
INSERT INTO Images(Name, Url) VALUES ('two hours later','https://images.funplay8.com/test/two_hours_later.jpg');
INSERT INTO Images(Name, Url) VALUES ('will smith   tada','https://images.funplay8.com/test/will_smith___tada.jpg');
INSERT INTO Images(Name, Url) VALUES ('wonka','https://images.funplay8.com/test/wonka.jpg');
INSERT INTO Images(Name, Url) VALUES ('wonka yao','https://images.funplay8.com/test/wonka_yao.jpg');
INSERT INTO Images(Name, Url) VALUES ('wow','https://images.funplay8.com/test/wow.jpg');
INSERT INTO Images(Name, Url) VALUES ('wut','https://images.funplay8.com/test/wut.jpg');
INSERT INTO Images(Name, Url) VALUES ('x all the y','https://images.funplay8.com/test/x_all_the_y.jpg');
INSERT INTO Images(Name, Url) VALUES ('y u no','https://images.funplay8.com/test/y_u_no.jpg');
INSERT INTO Images(Name, Url) VALUES ('y u no crying','https://images.funplay8.com/test/y_u_no_crying.jpg');
INSERT INTO Images(Name, Url) VALUES ('yao ming forever alone','https://images.funplay8.com/test/yao_ming_forever_alone.jpg');
INSERT INTO Images(Name, Url) VALUES ('yao ming pirate','https://images.funplay8.com/test/yao_ming_pirate.jpg');
INSERT INTO Images(Name, Url) VALUES ('yay','https://images.funplay8.com/test/yay.jpg');
INSERT INTO Images(Name, Url) VALUES ('yea science','https://images.funplay8.com/test/yea_science.jpg');
INSERT INTO Images(Name, Url) VALUES ('yes i do say','https://images.funplay8.com/test/yes_i_do_say.jpg');
INSERT INTO Images(Name, Url) VALUES ('yes this is dog','https://images.funplay8.com/test/yes_this_is_dog.jpg');
INSERT INTO Images(Name, Url) VALUES ('yesterday','https://images.funplay8.com/test/yesterday.jpg');
INSERT INTO Images(Name, Url) VALUES ('yo dawg','https://images.funplay8.com/test/yo_dawg.jpg');
INSERT INTO Images(Name, Url) VALUES ('you are the man','https://images.funplay8.com/test/you_are_the_man.jpg');
INSERT INTO Images(Name, Url) VALUES ('you dont say','https://images.funplay8.com/test/you_dont_say.jpg');
INSERT INTO Images(Name, Url) VALUES ('you fucking kidding me son','https://images.funplay8.com/test/you_fucking_kidding_me_son.jpg');
INSERT INTO Images(Name, Url) VALUES ('you got it','https://images.funplay8.com/test/you_got_it.jpg');
INSERT INTO Images(Name, Url) VALUES ('you seem upset','https://images.funplay8.com/test/you_seem_upset.jpg');
INSERT INTO Images(Name, Url) VALUES ('you win this time','https://images.funplay8.com/test/you_win_this_time.jpg');
INSERT INTO Images(Name, Url) VALUES ('your pain amuses me','https://images.funplay8.com/test/your_pain_amuses_me.jpg');
INSERT INTO Images(Name, Url) VALUES ('youre the man','https://images.funplay8.com/test/youre_the_man.jpg');